services:
  db:
    image: postgres:16
    container_name: emissions_db
    environment:
      POSTGRES_DB: 2026_Climate_Project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  backend:
    image: ghcr.io/deljod22/backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/2026_Climate_Project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres