spring.application.name=austrian_emissions

spring.datasource.url=jdbc:postgresql://localhost:5432/2026_Climate_Project
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect