spring.application.name=austrian_emissions

spring.datasource.url=jdbc:postgresql://localhost:5432/emissions
spring.datasource.username=emissions_user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect