GET localhost:8080/api/v1/test

### // Detailed Emissions

GET localhost:8080/api/v1/emissionDetailed

###

GET localhost:8080/api/v1/emissionDetailed?region=Steiermark

###

GET localhost:8080/api/v1/emissionDetailed?region=Steiermark&year=2000

###

GET localhost:8080/api/v1/emissionDetailed?region=Steiermark&year=2000&sector=Verkehr

###

GET localhost:8080/api/v1/emissionDetailed?endYear=2000

### // Total Emissions

GET localhost:8080/api/v1/totalEmissions

###

GET localhost:8080/api/v1/totalEmissions?region=Steiermark&year=2022

### // Emissions Per Capita

GET localhost:8080/api/v1/emissionPerCapita?region=Steiermark&year=2001

### // Total Emissions Per Capita

GET localhost:8080/api/v1/totalEmissionPerCapita?region=Steiermark&year=2000